version: '3.8'

services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - "8081:8080"
      - "5006:5005"
    depends_on:
      - order-db
    environment:
      - DATABASE_HOSTNAME=order-db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password1
      - SPRING_PROFILES_ACTIVE
    restart: always

  order-db:
    image: mysql:8
    container_name: order-db
    ports:
      - "3307:3306"
    volumes:
      - order-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_ROOT_PASSWORD: password1
    restart: always

volumes:
    order-db: {}